% Keywords for Group 2: Elliptic curves / CM theory

keyword(2, 'Elliptic curves / CM theory', 'elliptic').
keyword(2, 'Elliptic curves / CM theory', 'curve').
keyword(2, 'Elliptic curves / CM theory', 'weierstrass').
keyword(2, 'Elliptic curves / CM theory', 'j_invariant').
keyword(2, 'Elliptic curves / CM theory', 'modular').
keyword(2, 'Elliptic curves / CM theory', 'torsion').
keyword(2, 'Elliptic curves / CM theory', 'rank').
keyword(2, 'Elliptic curves / CM theory', 'mordell').
keyword(2, 'Elliptic curves / CM theory', 'weil').
keyword(2, 'Elliptic curves / CM theory', 'height').
keyword(2, 'Elliptic curves / CM theory', 'canonical').
keyword(2, 'Elliptic curves / CM theory', 'discriminant').
keyword(2, 'Elliptic curves / CM theory', 'conductor').
keyword(2, 'Elliptic curves / CM theory', 'isogeny').
keyword(2, 'Elliptic curves / CM theory', 'endomorphism').
keyword(2, 'Elliptic curves / CM theory', 'complex_multiplication').
keyword(2, 'Elliptic curves / CM theory', 'cm').
keyword(2, 'Elliptic curves / CM theory', 'imaginary').
keyword(2, 'Elliptic curves / CM theory', 'quadratic').
keyword(2, 'Elliptic curves / CM theory', 'field').
keyword(2, 'Elliptic curves / CM theory', 'class').
keyword(2, 'Elliptic curves / CM theory', 'number').
keyword(2, 'Elliptic curves / CM theory', 'hilbert').
keyword(2, 'Elliptic curves / CM theory', 'singular').
keyword(2, 'Elliptic curves / CM theory', 'moduli').
keyword(2, 'Elliptic curves / CM theory', 'l_function').
keyword(2, 'Elliptic curves / CM theory', 'functional').
keyword(2, 'Elliptic curves / CM theory', 'equation').
keyword(2, 'Elliptic curves / CM theory', 'euler').
keyword(2, 'Elliptic curves / CM theory', 'product').
keyword(2, 'Elliptic curves / CM theory', 'dirichlet').
keyword(2, 'Elliptic curves / CM theory', 'series').
keyword(2, 'Elliptic curves / CM theory', 'analytic').
keyword(2, 'Elliptic curves / CM theory', 'continuation').
keyword(2, 'Elliptic curves / CM theory', 'critical').
keyword(2, 'Elliptic curves / CM theory', 'rational').
keyword(2, 'Elliptic curves / CM theory', 'point').
keyword(2, 'Elliptic curves / CM theory', 'torsion').
keyword(2, 'Elliptic curves / CM theory', 'group').
keyword(2, 'Elliptic curves / CM theory', 'galois').
keyword(2, 'Elliptic curves / CM theory', 'representation').
keyword(2, 'Elliptic curves / CM theory', 'frobenius').
keyword(2, 'Elliptic curves / CM theory', 'trace').
keyword(2, 'Elliptic curves / CM theory', 'norm').
keyword(2, 'Elliptic curves / CM theory', 'reduction').
keyword(2, 'Elliptic curves / CM theory', 'modular_form').
keyword(2, 'Elliptic curves / CM theory', 'cusp').
keyword(2, 'Elliptic curves / CM theory', 'eisenstein').
keyword(2, 'Elliptic curves / CM theory', 'hecke').
keyword(2, 'Elliptic curves / CM theory', 'operator').
keyword(2, 'Elliptic curves / CM theory', 'newform').
keyword(2, 'Elliptic curves / CM theory', 'oldform').
keyword(2, 'Elliptic curves / CM theory', 'level').
keyword(2, 'Elliptic curves / CM theory', 'weight').
keyword(2, 'Elliptic curves / CM theory', 'character').
keyword(2, 'Elliptic curves / CM theory', 'sage').
keyword(2, 'Elliptic curves / CM theory', 'pari').
keyword(2, 'Elliptic curves / CM theory', 'magma').
keyword(2, 'Elliptic curves / CM theory', 'compute').
keyword(2, 'Elliptic curves / CM theory', 'algorithm').
keyword(2, 'Elliptic curves / CM theory', 'schoof').
keyword(2, 'Elliptic curves / CM theory', 'baby_step').
keyword(2, 'Elliptic curves / CM theory', 'giant_step').
keyword(2, 'Elliptic curves / CM theory', 'point_counting').
keyword(2, 'Elliptic curves / CM theory', 'discrete_log').
keyword(2, 'Elliptic curves / CM theory', 'bsd').
keyword(2, 'Elliptic curves / CM theory', 'conjecture').
keyword(2, 'Elliptic curves / CM theory', 'iwasawa').
keyword(2, 'Elliptic curves / CM theory', 'selmer').
keyword(2, 'Elliptic curves / CM theory', 'sha').
keyword(2, 'Elliptic curves / CM theory', 'regulator').

% Search for keyword in group 2
search_group_2(Keyword) :-
    keyword(2, _, Keyword),
    format('Found: ~w~n', [Keyword]).
