#!/bin/bash
ollama create qwen-shard-1 -f shards/modelfiles/Modelfile.1
ollama create qwen-shard-2 -f shards/modelfiles/Modelfile.2
ollama create qwen-shard-3 -f shards/modelfiles/Modelfile.3
ollama create qwen-shard-4 -f shards/modelfiles/Modelfile.4
ollama create qwen-shard-5 -f shards/modelfiles/Modelfile.5
ollama create qwen-shard-6 -f shards/modelfiles/Modelfile.6
ollama create qwen-shard-7 -f shards/modelfiles/Modelfile.7
ollama create qwen-shard-8 -f shards/modelfiles/Modelfile.8
ollama create qwen-shard-9 -f shards/modelfiles/Modelfile.9
ollama create qwen-shard-10 -f shards/modelfiles/Modelfile.10
ollama create qwen-shard-11 -f shards/modelfiles/Modelfile.11
ollama create qwen-shard-12 -f shards/modelfiles/Modelfile.12
ollama create qwen-shard-13 -f shards/modelfiles/Modelfile.13
ollama create qwen-shard-14 -f shards/modelfiles/Modelfile.14
ollama create qwen-shard-15 -f shards/modelfiles/Modelfile.15
ollama create qwen-shard-16 -f shards/modelfiles/Modelfile.16
ollama create qwen-shard-17 -f shards/modelfiles/Modelfile.17
ollama create qwen-shard-18 -f shards/modelfiles/Modelfile.18
ollama create qwen-shard-19 -f shards/modelfiles/Modelfile.19
ollama create qwen-shard-20 -f shards/modelfiles/Modelfile.20
ollama create qwen-shard-21 -f shards/modelfiles/Modelfile.21
ollama create qwen-shard-22 -f shards/modelfiles/Modelfile.22
ollama create qwen-shard-23 -f shards/modelfiles/Modelfile.23
ollama create qwen-shard-24 -f shards/modelfiles/Modelfile.24
ollama create qwen-shard-25 -f shards/modelfiles/Modelfile.25
ollama create qwen-shard-26 -f shards/modelfiles/Modelfile.26
ollama create qwen-shard-27 -f shards/modelfiles/Modelfile.27
ollama create qwen-shard-28 -f shards/modelfiles/Modelfile.28
ollama create qwen-shard-29 -f shards/modelfiles/Modelfile.29
ollama create qwen-shard-30 -f shards/modelfiles/Modelfile.30
ollama create qwen-shard-31 -f shards/modelfiles/Modelfile.31
ollama create qwen-shard-32 -f shards/modelfiles/Modelfile.32
ollama create qwen-shard-33 -f shards/modelfiles/Modelfile.33
ollama create qwen-shard-34 -f shards/modelfiles/Modelfile.34
ollama create qwen-shard-35 -f shards/modelfiles/Modelfile.35
ollama create qwen-shard-36 -f shards/modelfiles/Modelfile.36
ollama create qwen-shard-37 -f shards/modelfiles/Modelfile.37
ollama create qwen-shard-38 -f shards/modelfiles/Modelfile.38
ollama create qwen-shard-39 -f shards/modelfiles/Modelfile.39
ollama create qwen-shard-40 -f shards/modelfiles/Modelfile.40
ollama create qwen-shard-41 -f shards/modelfiles/Modelfile.41
ollama create qwen-shard-42 -f shards/modelfiles/Modelfile.42
ollama create qwen-shard-43 -f shards/modelfiles/Modelfile.43
ollama create qwen-shard-44 -f shards/modelfiles/Modelfile.44
ollama create qwen-shard-45 -f shards/modelfiles/Modelfile.45
ollama create qwen-shard-46 -f shards/modelfiles/Modelfile.46
ollama create qwen-shard-47 -f shards/modelfiles/Modelfile.47
ollama create qwen-shard-48 -f shards/modelfiles/Modelfile.48
ollama create qwen-shard-49 -f shards/modelfiles/Modelfile.49
ollama create qwen-shard-50 -f shards/modelfiles/Modelfile.50
ollama create qwen-shard-51 -f shards/modelfiles/Modelfile.51
ollama create qwen-shard-52 -f shards/modelfiles/Modelfile.52
ollama create qwen-shard-53 -f shards/modelfiles/Modelfile.53
ollama create qwen-shard-54 -f shards/modelfiles/Modelfile.54
ollama create qwen-shard-55 -f shards/modelfiles/Modelfile.55
ollama create qwen-shard-56 -f shards/modelfiles/Modelfile.56
ollama create qwen-shard-57 -f shards/modelfiles/Modelfile.57
ollama create qwen-shard-58 -f shards/modelfiles/Modelfile.58
ollama create qwen-shard-59 -f shards/modelfiles/Modelfile.59
ollama create qwen-shard-60 -f shards/modelfiles/Modelfile.60
ollama create qwen-shard-61 -f shards/modelfiles/Modelfile.61
ollama create qwen-shard-62 -f shards/modelfiles/Modelfile.62
ollama create qwen-shard-63 -f shards/modelfiles/Modelfile.63
ollama create qwen-shard-64 -f shards/modelfiles/Modelfile.64
ollama create qwen-shard-65 -f shards/modelfiles/Modelfile.65
ollama create qwen-shard-66 -f shards/modelfiles/Modelfile.66
ollama create qwen-shard-67 -f shards/modelfiles/Modelfile.67
ollama create qwen-shard-68 -f shards/modelfiles/Modelfile.68
ollama create qwen-shard-69 -f shards/modelfiles/Modelfile.69
ollama create qwen-shard-70 -f shards/modelfiles/Modelfile.70
ollama create qwen-shard-71 -f shards/modelfiles/Modelfile.71
